[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File /etc/fluent-bit/parsers.conf

[INPUT]
    Name              tail
    Path              /home/*/demoProjectLogs/tasosApp.json
    Tag               springboot_logs
    Parser            json
    Mem_Buf_Limit     5MB
    Read_from_Head    On

[INPUT]
    Name              tail
    Path              /home/*/demoProjectLogs/access_log*.log
    Tag               tomcat_access
    Parser            tomcat_access_parser
    Mem_Buf_Limit     5MB
    Read_from_Head    On

[FILTER]
    Name              record_modifier
    Match             tomcat_access
    Record            traffic_type human

[FILTER]
    Name              lua
    Match             tomcat_access
    Script            /etc/fluent-bit/enrich.lua
    Call              enrich

[OUTPUT]
    Name              opensearch
    Match             springboot_logs
    Host              10.0.0.71
    Port              9200
    HTTP_User         admin
    HTTP_Passwd       YOUR_OPENSEARCH_PASSWORD
    Logstash_Format   On
    Logstash_Prefix   springboot-logs
    tls               On
    tls.verify        Off
    Suppress_Type_Name On
    Retry_Limit       False
    Buffer_Size       10MB

[OUTPUT]
    Name              opensearch
    Match             tomcat_access
    Host              10.0.0.71
    Port              9200
    HTTP_User         admin
    HTTP_Passwd       YOUR_OPENSEARCH_PASSWORD
    Logstash_Format   On
    Logstash_Prefix   tomcat-access-logs
    tls               On
    tls.verify        Off
    Suppress_Type_Name On
    Retry_Limit       False
    Buffer_Size       10MB
    Pipeline          tomcat-geoip
