[PARSER]
    Name        json
    Format      json
    Time_Key    @timestamp
    Time_Format %Y-%m-%dT%H:%M:%S.%LZ

[PARSER]
    Name        tomcat_access_parser
    Format      regex
    Regex       ^(?<client_ip>[^ ]+) [^ ]+ [^ ]+ \[(?<request_time>[^\]]+)\] "(?<method>[A-Z]+) (?<request_path>[^ ]+) HTTP/[0-9.]+" (?<status_code>[0-9]+) (?<bytes_out>[0-9]+|-) (?<response_time_ms>[0-9]+|-) "(?<referer>[^"]*)" "(?<user_agent>[^"]*)"
    Time_Key    request_time
    Time_Format %d/%b/%Y:%H:%M:%S %z
    Types       status_code:integer response_time_ms:integer
